import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import ProviderWrapper from "@/lib/ProviderWrapper";
import { Toaster } from "@/components/ui/toaster";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} dark bg-[url('/bg.png')]`}>
        <ProviderWrapper>
          <Navbar />
          <div className="min-h-screen p-4 ">{children}</div>
          <Footer />
          <Toaster />
        </ProviderWrapper>
      </body>
    </html>
  );
}
