export const laptopModels: Model[] = [
  {
    docid: "model-1",
    company: "Lenovo",
    name: "ThinkPad X1 Carbon",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-2",
    company: "Lenovo",
    name: "Yoga C940",
    years: [2019, 2020],
    verified: true,
  },
  {
    docid: "model-3",
    company: "Lenovo",
    name: "Legion 7i",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-4",
    company: "HP",
    name: "HP Spectre x360",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-5",
    company: "HP",
    name: "HP Envy 13",
    years: [2019, 2020],
    verified: true,
  },
  {
    docid: "model-6",
    company: "Acer",
    name: "Acer Swift 3",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-7",
    company: "Acer",
    name: "Acer Predator Helios 300",
    years: [2019, 2020],
    verified: true,
  },
  {
    docid: "model-8",
    company: "Dell",
    name: "Dell XPS 13",
    years: [2019, 2020],
    verified: true,
  },
  {
    docid: "model-9",
    company: "Dell",
    name: "Dell Inspiron 15",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-10",
    company: "Apple",
    name: "MacBook Pro",
    years: [2020, 2021],
    verified: true,
  },
  {
    docid: "model-11",
    company: "Apple",
    name: "MacBook Air",
    years: [2020, 2021],
    verified: true,
  },
];
